# Generated by Django 4.2.3 on 2024-05-03 12:37

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=200,
                validators=[news.validators.validate_class_attributes],
            ),
        ),
    ]
